//! Migration types for shadow schema versioning
//!
//! These types support field-level migration when the shadow schema changes:
//! - Renamed fields: `#[shadow_attr(migrate(from = "old_name"))]`
//! - Converted values: `#[shadow_attr(migrate(convert = fn_name))]`
//! - Multiple sources: `#[shadow_attr(migrate(from = "old1"), migrate(from = "old2"))]`

/// Type alias for migration conversion functions.
///
/// Takes old value bytes, writes new value bytes to output buffer, returns new length.
pub type ConvertFn = fn(&[u8], &mut [u8]) -> Result<usize, MigrationError>;

/// Migration metadata for a single field.
///
/// Generated by the derive macro for fields with `#[shadow_attr(migrate(...))]`.
#[derive(Debug, Clone)]
pub struct MigrationSource {
    /// The old key path (relative to shadow prefix)
    pub key: &'static str,

    /// Optional conversion function.
    ///
    /// Takes old value bytes, writes new value bytes, returns new length.
    /// If `None`, the value is copied as-is (compatible format).
    pub convert: Option<ConvertFn>,
}

/// Errors that can occur during migration
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "defmt", derive(defmt::Format))]
pub enum MigrationError {
    /// Source key not found in KV store
    SourceNotFound,

    /// Conversion function failed
    ConversionFailed,

    /// Buffer too small for converted value
    BufferTooSmall,

    /// Invalid source value format
    InvalidSourceFormat,
}

/// Result of a `StateStore::load()` operation.
///
/// Provides detailed information about what happened during load,
/// useful for logging and diagnostics.
#[derive(Debug, Clone)]
pub struct LoadResult<S> {
    /// The loaded state
    pub state: S,

    /// Number of fields loaded from storage
    pub fields_loaded: usize,

    /// Number of fields migrated from old keys
    pub fields_migrated: usize,

    /// Number of fields using default values (not in storage)
    pub fields_defaulted: usize,

    /// Whether the schema hash changed (requires migration check)
    pub schema_changed: bool,

    /// Whether this is a first boot (no existing data)
    pub first_boot: bool,
}

impl<S: Default> Default for LoadResult<S> {
    fn default() -> Self {
        Self {
            state: S::default(),
            fields_loaded: 0,
            fields_migrated: 0,
            fields_defaulted: 0,
            schema_changed: false,
            first_boot: false,
        }
    }
}

impl<S: Default> LoadResult<S> {
    /// Create a result for first boot (all defaults)
    pub fn first_boot(total_fields: usize) -> Self {
        Self {
            state: S::default(),
            fields_loaded: 0,
            fields_migrated: 0,
            fields_defaulted: total_fields,
            schema_changed: false,
            first_boot: true,
        }
    }
}

impl<S> LoadResult<S> {
    /// Create a result with the given state
    pub fn with_state(state: S) -> Self {
        Self {
            state,
            fields_loaded: 0,
            fields_migrated: 0,
            fields_defaulted: 0,
            schema_changed: false,
            first_boot: false,
        }
    }

    /// Total number of fields processed
    pub fn total_fields(&self) -> usize {
        self.fields_loaded + self.fields_migrated + self.fields_defaulted
    }

    /// True if any migration occurred
    pub fn had_migrations(&self) -> bool {
        self.fields_migrated > 0
    }
}
